In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from neo4j import GraphDatabase, Result
from tqdm import tqdm
from typing import Dict, Any
from langchain_community.graphs import Neo4jGraph
from langchain_community.vectorstores import Neo4jVector

import pandas as pd

In [3]:
# user defined imports
from prompts import *
import helpers

In [4]:
import warnings

warnings.filterwarnings("ignore", category=FutureWarning)

## Parameters

In [5]:
path = "~/kg_aug_causal_disc_exp"

## Setting Up Graph

In [6]:
from config import NEO4J_URI, NEO4J_USERNAME, NEO4J_PASSWORD,NEO4J_DATABASE, DIRECTORY

driver = GraphDatabase.driver(NEO4J_URI, auth=(NEO4J_USERNAME, NEO4J_PASSWORD),database=NEO4J_DATABASE)

def db_query(cypher: str, params: Dict[str, Any] = {}) -> pd.DataFrame:
    """Executes a Cypher statement and returns a DataFrame"""
    return driver.execute_query(
        cypher, parameters_=params, result_transformer_=Result.to_df
    )

In [7]:
graph = Neo4jGraph(
    url=NEO4J_URI,
    username=NEO4J_USERNAME,
    password=NEO4J_PASSWORD,
    database=NEO4J_DATABASE,
    refresh_schema=False,
    driver_config={"notifications_disabled_classifications": ["DEPRECATION"]}
)

/tmp/ipykernel_916031/1094186590.py:1: LangChainDeprecationWarning: The class `Neo4jGraph` was deprecated in LangChain 0.3.8 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-neo4j package and should be used instead. To use it run `pip install -U :class:`~langchain-neo4j` and import as `from :class:`~langchain_neo4j import Neo4jGraph``.
  graph = Neo4jGraph(
/shared/graphrag/lib/python3.10/site-packages/langchain_community/graphs/neo4j_graph.py:404: PreviewWarning: notifications_disabled_classifications is a preview feature. It might be changed without following the deprecation policy. See also https://github.com/neo4j/neo4j-python-driver/wiki/preview-features.
  self._driver = neo4j.GraphDatabase.driver(

## Setting up LLM

In [8]:
from pydantic import BaseModel, Field
from typing import List

class Reasoning_Step(BaseModel):
    reasoning_step: str = Field(..., description="An intermediate reasoning step for breaking down the given context and query")

class Answer(BaseModel):
    reasoning: List[Reasoning_Step] = Field(..., description="List of reasoning steps")
    conclusion: bool = Field(..., description="The culminating final conclusion or answer to the question")

In [9]:
from llm_client import get_client
generator = get_client(schema=Answer)

# Local Retriever

In [10]:
# parameters for the local search query
from config import topChunks, topCommunities, topRels, topEntities

lc_retrieval_query = helpers.load_query("local_search.cypher")
kw_retrieval_query = helpers.load_query("keyword_search.cypher")

In [11]:
# variables of interest
with open("variable_definitions/default_definitions.json", "r") as file:
    def_map = json.load(file)

In [12]:
db_query(
    """
    CREATE VECTOR INDEX vector IF NOT EXISTS
    FOR (n:__Entity__)
    ON n.embedding
    OPTIONS {indexConfig: {
      `vector.dimensions`: 768,
      `vector.similarity_function`: "cosine"
    }};
    """
)

Empty DataFrame
Columns: []
Index: []

In [13]:
db_query("SHOW INDEXES")

,id,name,state,populationPercent,type,entityType,labelsOrTypes,properties,indexProvider,owningConstraint,lastRead,readCount
0,8,constraint_8be13a40,ONLINE,100.0,RANGE,NODE,[__Community__],[id],range-1.0,constraint_8be13a40,2025-12-05T20:27:49.504000000+00:00,220440
1,1,constraint_907a464e,ONLINE,100.0,RANGE,NODE,[__Entity__],[id],range-1.0,constraint_907a464e,2025-12-04T22:30:49.273000000+00:00,132894
2,6,vector,ONLINE,100.0,VECTOR,NODE,[__Entity__],[embedding],vector-1.0,None,2025-12-09T18:31:48.014000000+00:00,4364

In [14]:
from langchain_community.embeddings import HuggingFaceEmbeddings
import torch

embedding = HuggingFaceEmbeddings(
    model_name="pritamdeka/S-PubMedBert-MS-MARCO",
    model_kwargs={'device': 'cuda' if torch.cuda.is_available() else 'cpu'},
    encode_kwargs={'normalize_embeddings': True}
)

/tmp/ipykernel_916031/2722532535.py:4: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-huggingface package and should be used instead. To use it run `pip install -U :class:`~langchain-huggingface` and import as `from :class:`~langchain_huggingface import HuggingFaceEmbeddings``.
  embedding = HuggingFaceEmbeddings(

In [15]:
lc_retrieval_query = helpers.load_query("local_search.cypher")
lc_vector = Neo4jVector.from_existing_index(
    embedding=embedding,
    url=NEO4J_URI,
    username=NEO4J_USERNAME,
    password=NEO4J_PASSWORD,
    database=NEO4J_DATABASE,
    index_name="vector", # may need to alter
    search_type="vector",
    # keyword_index_name="keyword",
    retrieval_query=lc_retrieval_query,
)

In [16]:
from helpers import *
from build_context import stringify_report, format_triplet, construct_query_context
from config import query_context_window

def retrieve_context_query(query) -> str:

    res = lc_vector.similarity_search(
        query,
        k=topEntities,
        params={
            "topChunks": topChunks,
            "topCommunities": topCommunities,
            "topRels": topRels
        }
    )

    metadata = res[0].metadata
    reports = [stringify_report(report) for report in metadata["Reports"]]
    chunks = metadata["Chunks"]
    relationships = [format_triplet(triplet) for triplet in metadata["Relationships"]]

    return construct_query_context(relationships, chunks, reports, max_context_window=query_context_window)

In [17]:
def local_retriever(query, var1, var2, summary, debug=False):
    if debug:
        print(reduce(query, var1, var2, summary, def_map))
    response = generator(reduce(query, var1, var2, summary, def_map), sampling_params={"n":1, "temperature":0.0, "top_k":1})

    return response.conclusion, helpers.reasoning_to_string(response)

In [18]:
def llm_retriever(query, var1, var2, debug=False):
    if debug:
        print(predict(query, var1, var2, def_map))
    response = generator(predict(query, var1, var2, def_map), sampling_params={"n":1, "temperature":0.0, "top_k":1})
    return response.conclusion, helpers.reasoning_to_string(response)

In [19]:
from promptsd.query_prompts import plausibility_prompt, temporality_prompt, causal_lit_prompt, association_prompt

def query_local_causality(row):
    var1, var2, label = row['var1'], row['var2'], row["label"]
    # bandaid for now
    var1 = "Sleep disturbance" if var1 == "Sleep" else var1
    var2 = "Sleep disturbance" if var2 == "Sleep" else var2
        
    report = retrieve_context_query(var1, var2)
    pquery = plausibility_prompt(var1, var2)
    aquery = association_prompt(var1, var2)
    tquery = temporality_prompt(var1, var2)
    plausibility, preasoning = local_retriever(pquery, var1, var2, report)
    association, areasoning = local_retriever(aquery, var1, var2, report)
    temporality, treasoning = local_retriever(tquery, var1, var2, report)
    return [var1, var2, plausibility, preasoning, association, areasoning, temporality, treasoning, report, label]

In [20]:
def query_llm_causality(row):
    var1, var2, label = row['var1'], row['var2'], row["label"]
    # bandaid for now
    var1 = "Sleep disturbance" if var1 == "Sleep" else var1
    var2 = "Sleep disturbance" if var2 == "Sleep" else var2
        
    pquery = plausibility_prompt(var1, var2)
    aquery = association_prompt(var1, var2)
    tquery = temporality_prompt(var1, var2)
    plausibility, preasoning = llm_retriever(pquery, var1, var2)
    association, areasoning = llm_retriever(aquery, var1, var2)
    temporality, treasoning = llm_retriever(tquery, var1, var2)
    return [var1, var2, plausibility, preasoning, association, areasoning, temporality, treasoning, label]

In [21]:
full = pd.read_csv(f"{path}/data/full_cleaned.csv").drop(columns=["Unnamed: 0"])

# Experiments

## LLM

In [ ]:
from prompts import *
res = full.apply(query_llm_causality, axis=1)

In [ ]:
columns = "Var1", "Var2", "Plausibility", "Plausibility Reasoning", "Association", "Association Reasoning", "Temporality", "Temporality Reasoning", "Label"
llm_res = pd.DataFrame(res.to_list(), columns=columns)
llm_res.to_csv("results/llm.csv")
llm_res

In [ ]:
from sklearn.metrics import f1_score
print("RESULTS FOR LLM ONLY")
print(f1_score(llm_res["Label"], llm_res["Plausibility"]))

In [ ]:
print(llm_res["Plausibility"].value_counts())

## Local Search

In [173]:
from prompts import *
res = full.apply(query_local_causality, axis=1)

NameError: name 'full' is not defined

In [ ]:
columns = "Var1", "Var2", "Plausibility", "Plausibility Reasoning", "Association", "Association Reasoning", "Temporality", "Temporality Reasoning", "Report", "Label"
local_res = pd.DataFrame(res.to_list(), columns=columns)
local_res.to_csv("results/kgrag.csv")
local_res

In [ ]:
from sklearn.metrics import f1_score
print("RESULTS FOR LOCAL")
print(f1_score(local_res["Label"], local_res["Plausibility"]))

In [ ]:
print(local_res["Plausibility"].value_counts())

# Toy Example

In [44]:
from helpers import *
from build_context import stringify_report, format_triplet, construct_query_context
from config import query_context_window, topEntities

def retrieve_context_query(query) -> str:

    res = lc_vector.similarity_search(
        query,
        k=topEntities,
        params={
            "topChunks": topChunks,
            "topCommunities": topCommunities,
            "topRels": topRels
        }
    )

    metadata = res[0].metadata
    print(metadata["Reports"])
    reports = [stringify_report(report) for report in metadata["Reports"]]
    chunks = metadata["Chunks"]
    relationships = [format_triplet(triplet) for triplet in metadata["Relationships"]]

    return construct_query_context(relationships, chunks, reports, max_context_window=query_context_window)

In [45]:
lc_retrieval_query = helpers.load_query("local_search.cypher")
lc_vector = Neo4jVector.from_existing_index(
    embedding=embedding,
    url=NEO4J_URI,
    username=NEO4J_USERNAME,
    password=NEO4J_PASSWORD,
    database=NEO4J_DATABASE,
    index_name="vector", # may need to alter
    search_type="vector",
    # keyword_index_name="keyword",
    retrieval_query=lc_retrieval_query,
)

In [46]:
def local_retriever(query, var1, var2, summary, debug=False):
    if debug:
        print(reduce(query, var1, var2, summary, def_map))
    response = generator(reduce(query, var1, var2, summary, def_map), sampling_params={"n":1, "temperature":0.0, "top_k":1})

    return response.conclusion, helpers.reasoning_to_string(response)

In [71]:
from promptsd.query_prompts import plausibility_prompt, temporality_prompt, association_prompt
from prompts_directions import DIRECT_CAUSAL_PROMPT
from prompts import reduce


var1, var2 = "Alcohol", "Financial_level"
query = association_prompt(var1, var2)
report = retrieve_context_query(f"{def_map.get(var1)} {def_map.get(var2)}")
answer = local_retriever(query, var1, var2, report, debug=True)

[{'detailed_findings': ['Alcohol consumption may be associated with sleep disturbances: The text suggests that alcohol consumption may be associated with various sleep disturbances, including insomnia, obstructive sleep apnea, circadian abnormalities, short sleep duration, and poor sleep quality. Alcohol consumption, particularly binge drinking, has been linked to adverse health effects and sleep problems.', 'Alcohol consumption may affect fear avoidance beliefs: The text indicates that alcohol consumption may affect fear avoidance beliefs, potentially contributing to increased fear avoidance. This may be due to impaired judgment or increased risk-taking associated with alcohol use.', 'Alcohol consumption may be associated with financial level: The text suggests that there may be an association between financial level and alcohol consumption, as financial constraints can affect the ability to afford alcohol. However, the relationship is not explicitly stated, and it is possible that financial level could influence alcohol consumption.', "Alcohol consumption may be associated with increased anxiety: The text indicates that anxiety is often associated with increased alcohol consumption. This may be due to alcohol's sedative effects, which can temporarily reduce anxiety, leading to increased consumption. However, long-term alcohol use can exacerbate anxiety symptoms.", "Alcohol consumption may be associated with depression: The text suggests that alcohol consumption may be associated with depression. This may be due to alcohol's effects on the brain, which can lead to mood changes and depressive symptoms. Long-term alcohol use can also contribute to depression."], 'summary': "This report examines the relationships between alcohol consumption and various factors, including sleep disturbance, fear avoidance, financial level, and mental health. The analysis reveals potential associations, correlations, and influences between alcohol consumption and these factors, shedding light on the complex interplay between alcohol use and other aspects of an individual's life.", 'impact_severity_rating': 7.5, 'level': 0, 'rating_explanation': "The potential impacts of alcohol consumption on various aspects of an individual's life, including sleep, fear avoidance, financial level, and mental health, warrant a high impact severity rating.", 'community_rank': 1386, 'id': '0-4991', 'title': 'Alcohol Consumption and Its Associations with Sleep Disturbance, Fear Avoidance, Financial Level, and Mental Health'}, {'detailed_findings': ['Age and Education Level are interconnected: The analysis reveals that Age and Education Level are associated with each other, as older individuals may have completed their education at an earlier age, and higher education level may be associated with later age. This relationship is crucial in understanding the overall structure of the community.', 'Age influences education: The findings suggest that Age can influence Education Level, as older individuals may have completed their education at an earlier age. This relationship is important in understanding the educational attainment of different age groups.', 'Education level increases with age: The analysis shows that Education Level often increases with Age, as older individuals may have had more time to complete their education. This relationship is significant in understanding the educational attainment of different age groups.', 'Age and education level are demographic factors: Both Age and Education Level are demographic factors that are used to categorize individuals and understand their characteristics. These factors are important in various studies and research.', 'Age and education level are associated with socioeconomic status: The findings suggest that Age and Education Level are associated with socioeconomic status, as older individuals and those with higher education levels may have better financial resources and opportunities.', 'Age and education level are associated with health: The analysis reveals that Age and Education Level are associated with health, as older individuals and those with lower education levels may have poorer health outcomes. This relationship is crucial in understanding the health disparities between different age and education groups.', 'Age and education level are associated with financial well-being: The findings suggest that Age and Education Level are associated with financial well-being, as older individuals and those with higher education levels may have better financial resources and stability.'], 'summary': "This report examines the community of Age and Education Level, two key demographic factors that are interconnected and influence various aspects of an individual's life. The analysis reveals associations between Age and Education Level, as well as their potential impacts on other variables such as income, health, and socioeconomic status. The community's entities include Age, Education Level, Participant, Respondent, and various study variables. The entities are related through associations, influences, and correlations, providing valuable insights into the relationships between these factors.", 'impact_severity_rating': 7.5, 'level': 0, 'rating_explanation': "The impact severity rating of 7.5 indicates a significant influence of Age and Education Level on various aspects of an individual's life, including health, socioeconomic status, and financial well-being.", 'community_rank': 1127, 'id': '0-92', 'title': 'Age and Education Level Community: Demographic Factors and Their Associations'}, {'detailed_findings': ['Anxiety and insomnia are interconnected: The analysis reveals a complex and mutual relationship between anxiety and insomnia, with each condition potentially causing and exacerbating the other. This interconnectedness suggests that addressing one condition may help alleviate symptoms of the other.', 'Insomnia may be a risk factor for the development of anxiety: The study suggests that insomnia may increase the risk of developing anxiety due to the disruption of circadian rhythms and reduced connectivity between the prefrontal cortex and the amyggdala.', 'Anxiety can contribute to insomnia: Anxiety can cause insomnia by contributing to physical symptoms such as restlessness, rapid heart rate, and difficulty breathing, which can make it difficult to fall asleep or stay asleep.', 'Insomnia and anxiety tend to be highly concurrent in the clinical setting: The analysis shows that insomnia and anxiety tend to occur together in the clinical setting, suggesting a strong association between the two conditions.', 'Insomnia and anxiety share genetic and environmental factors: The study suggests that insomnia and anxiety may share genetic or environmental factors, as patients with insomnia present with more signs of negative personality traits, such as neuroticism.', 'Insomnia symptoms are potentially causally associated with anxiety: The text indicates that insomnia symptoms, such as difficulty falling asleep, staying asleep, or waking up too early, are potentially causally associated with anxiety.', 'Insomnia has been found to be associated with an increased risk of anxiety: The study found a putative causal link of insomnia on anxiety, suggesting that insomnia may increase the risk of developing anxiety.', 'Physical activity can help alleviate insomnia: Physical activity can help alleviate insomnia by reducing stress and promoting relaxation, which can improve sleep quality.', 'Anxiety is associated with an increased risk of coronary heart disease: Anxiety is associated with an increased risk of coronary heart disease due to the disruption of circadian rhythms and increased stress levels, which can lead to cardiovascular problems.', 'Insomnia symptoms are associated with diabetes: Insomnia symptoms are associated with diabetes due to the disruption of circadian rhythms and increased stress levels, which can lead to metabolic imbalances.'], 'summary': "This report examines the relationship between anxiety and insomnia, two interconnected conditions that significantly impact individuals' mental and physical health. The analysis is based on a collection of studies and research findings, primarily focusing on the UK Biobank dataset. The report reveals a complex and mutual relationship between anxiety and insomnia, with each condition potentially causing and exacerbating the other. Additionally, the study suggests that insomnia may be a risk factor for the development of anxiety, while anxiety can contribute to the onset or worsening of insomnia.", 'impact_severity_rating': 8.5, 'level': 0, 'rating_explanation': "The high impact severity rating of 8.5 indicates the significant and widespread impact of the comorbidity between anxiety and insomnia on individuals' health and well-being.", 'community_rank': 639, 'id': '0-4699', 'title': 'Anxiety and Insomnia Community: A Comorbidity Analysis'}, {'detailed_findings': ['Depression is associated with an increased risk of developing arthritis: The text suggests that there is a strong association between depression and arthritis. Depression has been associated with an increased risk of developing arthritis, as well as an increased risk for arthritis in general. This association is supported by type II evidence.', 'Depression is associated with an increased risk of developing asthma: Depression has been associated with an increased risk of developing asthma. This association is supported by type II evidence.', 'Depression is associated with an increased risk of developing hypertension: Depression has been associated with an increased risk of developing hypertension. This association is supported by type II evidence.', 'Depression is associated with an increased risk of developing heart disease: Depression has been associated with an increased risk of developing heart disease. This association is supported by type II evidence.', 'Depression is associated with an increased risk of developing chronic physical conditions: The text suggests that depression is associated with an increased risk for chronic physical conditions. The study found that depression was associated with an increased risk of chronic physical conditions.', 'Depression is associated with an increased risk of developing osteoporosis: Depression has been associated with an increased risk of developing osteoporosis. This association is supported by type II evidence.', 'Depression is associated with an increased risk of headache: Depression is associated with an increased risk of headache. Depression was identified as a predisposing contributor for the risk of headache, and depression is a significant contributor to headache.', 'Depression is associated with an increased risk of COPD: Depression has been associated with an increased risk of developing COPD. Depression has been associated with an increased risk of COPD, and depression and COPD often occur together, with depression exacerbating the symptoms of COPD.', 'Depression is associated with unemployment: Unemployment has been identified as a risk factor for depression. The text suggests that individuals with depression may have problems with access to primary care, which can increase the risk of chronic physical conditions, and unemployment has been associated with an increased risk of depression.', 'Depression is associated with widowhood: Widowhood is significantly associated with depression. Widowhood is a known risk factor for depression, and widowhood is a risk factor for developing depression.'], 'summary': 'This report examines the community of depression, its subtypes, and its associations with various health outcomes, including arthritis, asthma, hypertension, heart disease, chronic physical conditions, osteoporosis, headache, COPD, and other comorbidities. The community also includes entities such as job strain, unemployment, widowhood, environmental risk factors, and psychotropic medications. The report provides insights into the causal relationships, risk factors, and bidirectional relationships between depression and these health outcomes.', 'impact_severity_rating': 8.5, 'level': 0, 'rating_explanation': 'The high impact severity rating is due to the significant association between depression and various health outcomes, as well as the potential for depression to exacerbate the symptoms of these conditions.', 'community_rank': 562, 'id': '0-4341', 'title': 'Depression and its Associated Health Outcomes'}, {'detailed_findings': ['Prevalence of Mental Health Issues: The report indicates that a significant number of adults suffer from mental health issues, including any mental illness (AMI) and serious mental illness (SMI). The prevalence of these issues varies among racial and ethnic subgroups, with Multiracial individuals having the highest percentage of AMI and SMI.', 'Substance Use Disorders: The report also discusses the prevalence of substance use disorders among adults. The most commonly abused substances include marijuana, cocaine, heroin, methamphetamine, prescription psychotherapeutic drugs, and hallucinogens. The prevalence of substance use disorders also varies among racial and ethnic subgroups.', 'Mental Health Treatment: The report shows that a significant number of adults receive mental health treatment, including prescription medication and substance use treatment. The availability and accessibility of mental health treatment vary among racial and ethnic subgroups.', 'Comparison of Young Adults and Adults: The report compares the mental health status of young adults to the overall adult population. Young adults are found to have a higher prevalence of mental health issues and substance use disorders compared to the overall adult population.', 'Racial and Ethnic Differences: The report compares the mental health status of various racial and ethnic subgroups. Some differences are found in the prevalence of mental health issues, substance use disorders, and mental health treatment among these subgroups.'], 'summary': 'This report focuses on the community of adults, aged 18 years or older, and their mental health. The community is composed of various racial and ethnic subgroups, including Asian, White, Multiracial, Hispanic, and Black or African American. The report examines the prevalence of mental health issues, substance use disorders, and mental health treatment among these subgroups. It also compares the mental health status of young adults, aged between 18 and 35, to the overall adult population.', 'impact_severity_rating': 8.5, 'level': 0, 'rating_explanation': "The high impact severity rating is due to the prevalence of mental health issues and substance use disorders among the adult population, as well as the potential consequences of these issues on individuals' lives and society as a whole.", 'community_rank': 466, 'id': '0-6581', 'title': 'Community of Adults and Their Mental Health'}, {'detailed_findings': ['Gender differences in financial hardship during the COVID-19 pandemic: The study found that both men and women experienced financial hardship during the COVID-19 pandemic, but women may have been disproportionately impacted. This is demonstrated by higher unemployment rates and lower financial literacy levels among women.', 'Gender and financial literacy: Previous research indicates that women have less financial knowledge than men, on average. This study found that gender is associated with financial literacy levels, with men having higher levels of financial literacy.', 'Gender and banking habits: Gender is found to influence banking habits, with men being more likely to be fully banked than women. Men are also more likely to use credit cards for making everyday purchases, shopping online, and borrowing money by carrying a balance past 30 days.', 'Gender and retirement outcomes: Men are a key demographic affected by retirement outcomes, as they are more likely to engage in retirement planning activities and have higher levels of retirement savings. Women, on the other hand, are less likely to engage in retirement planning and are less confident about applying for an additional credit card than men.', 'Gender and health outcomes: The study suggests that men may be more responsive to environmental cues and may be more likely to experience medication cost issues. Men with Medicare coverage and financial hardship have a lower odds of experiencing severe pain compared to men with financial hardship without Medicare coverage.', 'Gender and ethnicity: Men and women in the study had different ethnic backgrounds.', 'Women and financial hardship: The study suggests that women may have been disproportionately financially impacted by the COVID-19 pandemic, as demonstrated by higher unemployment rates.', 'Women and retirement: Women are disproportionately affected by retirement, as they live longer than men and are likely to be the primary financial decision maker in their household later in life.'], 'summary': "This report examines the relationships between gender, financial hardship, and various demographic factors within a community of individuals participating in a study during the COVID-19 pandemic. The study investigates the associations between financial hardship and sleep disturbances by gender, and finds that women may have been disproportionately impacted by financial hardship. Men and women were found to have different ethnic backgrounds, and gender is associated with financial literacy levels, banking habits, and retirement outcomes. The report also highlights potential implications for men's health outcomes and pain experiences due to factors such as Medicare coverage and financial hardship.", 'impact_severity_rating': 7.5, 'level': 0, 'rating_explanation': 'The study suggests that women may have been disproportionately impacted by financial hardship during the COVID-19 pandemic, with higher unemployment rates and lower financial literacy levels.', 'community_rank': 325, 'id': '0-3004', 'title': 'Gender and Financial Hardship during the COVID-19 Pandemic'}, {'detailed_findings': ['Patient Demographics: The community consists of patients with a wide age range (41-82 years), with a mean age of 59.1 years and a standard deviation of 10.2 years. This diversity in age may provide valuable insights into the prevalence and management of chronic low back pain across different age groups.', 'Study Participation: All patients in the community are participating in the UK Biobank study, which involves various medical procedures and assessments to validate the clinical diagnosis of nonspecific chronic low back pain and to rule out specific pathologies.', 'Language Requirement: German language proficiency is a requirement for inclusion in the study, which may limit the generalizability of the findings to non-German speaking populations.', 'Exclusion Criteria: Specific pathologies, pain intensity in a leg, sensory processing disorders, back surgery within the past three years, cognitive impairment, alcohol or substance abuse, neuropathy, inflammatory diseases, and cognitive impairment were used as exclusion criteria to ensure a homogeneous study population.', "Medical Procedures: The patients in the community undergo various medical procedures as part of the clinical evaluation, including blood tests, magnetic resonance imaging, X-rays, and sensory processing assessments. These procedures help to diagnose and manage the patients' chronic low back pain and rule out any underlying pathologies."], 'summary': "This report presents an analysis of a community consisting of patients with nonspecific chronic low back pain, recruited from a tertiary care pain center at the University Hospital Heidelberg. The community's key entities are the patients, the study design, and various medical procedures such as blood tests, magnetic resonance imaging, X-rays, and clinical evaluations. The patients were excluded based on specific pathologies, pai

In [72]:
print(answer[1])

Reasoning Process:
Step 1: The report provides several relationships between Alcohol and Financial_level, including 'Alcohol consumption may be associated with financial level', 'Alcohol consumption may affect financial level', 'There may be an association between financial level and alcohol consumption', and 'Financial level may influence alcohol consumption'. These relationships suggest a statistical dependency between the two variables.
Step 2: The absence of a relationship does not necessarily mean that there is no association. However, in this case, the multiple relationships provided in the report provide strong evidence of an association between Alcohol and Financial_level.

Conclusion: Yes

In [64]:
import helpers
helpers.token_count(report)

7993

In [55]:
print(report)

# Report:
## Chunks:

 al.,](#page-7-3) [2012\)](#page-7-3), and *moderate drinkers* (34.8%; defined as *current drinkers* who that have less than or equal to 210 g of ethanol per week). #### Genetic Instruments There are two genetic variants commonly used in MR studies of alcohol use: the alcohol dehydrogenase 1B gene (*ADH1B* rs1229984) and the aldehyde dehydrogenase 2 gene (*ALDH2* rs671), both of which encode enzymes involved in the metabolic pathway for ethanol and can change the metabolic balance of acetaldehyde in human body ([Peng and Yin, 2009\)](#page-7-5). In the human body, ethanol is first converted to acetaldehyde by alcohol dehydrogenase (ADH) and then to acetate by aldehyde dehydrogenase (ALDH). The enzyme activity of ADH and ALDH are largely determined by the number of effect alleles (i.e., A-allele) in both *ADH1B* rs1229984 and *ALDH2* rs671. In East Asian populations, *ALDH2* rs671 alleles exist with three genotypes, GG (# of A allele = 0), AG (# of A allele = 1), and AA (# of A allele = 2), where the presence of A allele can significantly decrease the detoxification of acetaldehyde generated during alcohol metabolism in humans as noted above ([Peng and Yin, 2009](#page-7-5); [Edenberg and McClintick, 2018\)](#page-6-10). From **[Table 1](#page-2-0)**, 35.5% of respondents in our sample are A-allele carriers (i.e., genotypes of AA and AG). Specifically, the percentages of genotype AA and AG are 4.5 and 31.0%, respectively. In European populations, *ADH1B* rs1229984 has been used as the principal genetic instrument in MR studies of alcohol use ([Holmes et al., 2014](#page-6-7)). But because the proportion of A-allele carriers is very low (around 3% in Europeans), these MR studies require much larger sample sizes.(#page-3-0) In comparison, a majority of participants are A-allele carriers of the *ADH1B* rs1229984 in our sample (AA: 42.4% and AG: 44.8%). # Measures of Depression The 10-item Center for Epidemiologic Studies Depression Scale (CESD-10) was used as a reliable and valid survey instrument to screen for symptoms of depression [\(Radloff, 1977;](#page-7-6) [Boey,](#page-6-11) [1999\)]
>de<br>for<br>l ef<br>fec<br>No<br>evi<br>ts<br>ar<br>nce<br>ca<br>usa | | 34 | Rit<br>chi<br>l.<br>t a<br>e e<br>(<br>4)<br>201 | Alc<br>oh<br>ol | Ind<br>ivid<br>ual<br>lev<br>el | Alc<br>oh<br>ol<br>in<br>da<br>use<br>gra<br>m<br>per<br>y<br>(se<br>lf-r<br>rt)<br>epo | itiv<br>e f<br>tio<br>nin<br>(<br>in-<br>Co<br>gn<br>unc<br>g<br>per<br>son<br>12)<br>Mo<br>Ho<br>Tes<br>t N<br>ray<br>use<br>o. | – | cle<br>evi<br>de<br>for<br>l ef<br>fec<br>No<br>ts<br>ar<br>nce<br>ca<br>usa<br>of<br>alc<br>oh<br>ol o<br>nit<br>ive<br>fun<br>ctio<br>nin<br>n c<br>og<br>g,<br>her<br>int<br>ctio<br>Ho<br>, t<br>we<br>ver<br>e w<br>as<br>an<br>era<br>n<br>h t<br>hat<br>ind<br>ivid<br>ual<br>ith<br>hig<br>her<br>suc<br>s w<br>eti<br>bili<br>lco<br>ho<br>l<br>ty<br>to<br>gen<br>c a<br>pro<br>ces<br>s a<br>sho<br>d r<br>ela<br>tive<br>im<br>s in<br>ent<br>we<br>pro<br>vem<br>nit<br>ive<br>ab<br>ility<br>wit<br>h m<br>cog<br>ore<br>tio<br>wh<br>tho<br>wit
·667% | 0·253% | 25·7 | 11·1% | 0·119% | | | (0·619 to 3·79) | (0·233 to 1·43) | (–0·161 to 0·738) | (17·3 to 36·8) | (7·45 to 15·9) | (–3·42 to 3·33) | | Mexico | | | | | | | | 15–39 years | 6570 | 25·2% | –2·75% | 15000 | 59·7% | –4·61% | | 40–64 years | (3930 to 8740) | (15·1 to 33·5) | (–10·3 to 4·67) | (12 200 to 16100) | (48·4 to 64·1) | (–10·3 to 1·09) | | | 1180 | 6·50% | –0·343% | 7170 | 43·7% | –5·88% | | ≥65 years | (659 to 1850) | (3·64 to 10·3) | (–3·94 to 2·67) | (6040 to 8670) | (36·8 to 52·8) | (–11·7 to –0·361) | | | 69·8 | 1·26% | 0·498% | 868 | 18·3% | –0·0786% | | | (25·6 to 150) | (0·463 to 2·71) | (–0·245 to 1·23) | (630 to 1170) | (13·3 to 24·7) | (–4·86 to 4·23) | | Nicaragua | | | | | | | | 15–39 years | 254 | 18·0% | –1·28% | 781 | 55·3% | –1·14% | | | (133 to 365) | (9·44 to 25·9) | (–8·09 to 4·69) | (593 to 854) | (42·0 to 60·5) | (–7·11 to 4·62) | | 40–64 years | 36·0 | 4·79% | 0·851% | 253 | 38·4% | –1·55% | | | (18·1 to 62·8) | (2·41 to 8·36) | (–1·69 to 2·94) | (204 to 323) | (30·9 to 48·9) | (–8·40 to 4·42) | | ≥65 years | 1·55 | 0·729% | 0·420% | 23·6 | 13·6% | 1
 a slight but noticeable association with pain reduction and mitigation of physical dysfunction [\(#page-9-5)]. Terefore, researchers are increasingly recognizing the intricate comorbidities and interactions between pain and mental disorders, where the two diseases often coexist and promote each other, and may be partially mediated by shared neural mechanisms [(#page-9-6)]. Addressing both the physical and psychological aspects of pain is crucial for managing this condition efectively and improving patients' quality of life. It has been reported [\(#page-9-7)] that there is a strong correlation between the prevalence of depression and the severity of pain in patients with lower back pain. Patients with severe pain experience higher levels of mental distress than those with mild or moderate pain. Moreover, observational studies [[9,](#page-9-8) [10\]](#page-9-9) have also found that the use of opioids is highly comorbid with depression, anxiety, and stress related disorders. Tese fndings underscore the importance of psychological interventions as an integral component of pain management, which can improve patients' mental health, help alleviate pain, and reduce reliance on opioids, and may be a potential alternative to medication analgesia in some cases [(#page-9-10)]. Despite previous research on the relationship between pain and psychological problems, the fndings have been inconclusive, and our understanding of this complex interaction remains limited. A recent MR study [(#page-9-11)] has identifed depression as a risk factor for pain localized in specifc regions, including the head, neck/shoulder, back, and abdomen/stomach. However, whether there are causal associations between other mental disorders and pain remain uncertain, which may pose challenges for further clinical application of psychological intervention. Addressing this gap in research through rigorous and systematic investigation of the complexities of the relationship between pain and mental health is necessary to develop efective and targeted psychological interventions that can beneft patients in need. Mendelian randomization (MR) involves the use of single nucleotide polymorphism (SNP) as instrumental variables to estimate the causal efect of exposure factors on outcomes [\(#page-9-12)]. Tis method is advantageous because genetic variants are randomly allocated during meiosis, minimizing confounding, measurement error, and reverse causation that can afict conventional multivariable regression approaches [[14\]](#page-9-13). Moreover, the genetic variations used in MR analyses are unrelated to confounding variables in the exposure-outcome relation, reducing the risk of bias, and enhancing the validity of causal inference [\(#page-9-14)]. Given the critical public health implications of assessing the bidirectional relationship between pain and mental disorders, obtaining robust causal inferences about these associations is critical for developing efective prevention and treatment strategies. Te primary aim of the study is to update and expand upon previous research
\]](#page-10-2). However, these cohorts included highly selected middle-to-high class subjects, highly educated subjects, or only health professionals. They also reported J-shaped associations for all-cause mortality. These effects might be dependent on the distribution of causes of death in the selected samples and on the distribution of levels of alcohol consumption in cohort participants, with few of them drinking high amounts or indulging in binge drinking [\[11\]](#page-9-0). This fact may compromise the strength of their potential causal inferences and generalizability [\(#page-10-3)[–46\]](#page-10-4). In addition, studies using genetic instrumental variables or Mendelian randomization (MR) analyses have challenged that moderate alcohol consumption may reduce CVD or total mortality and support complete abstention as the healthiest option [\[47–](#page-10-5)[50\]](#page-10-6). These analyses avoid the problems of self-selection for the drinking pattern, thus reducing confounding. They also provide a proxy of lifetime consumption and eliminate reverse causation. There are also limitations in MR analyses because, while MR analyses may contribute to identifying causal pathways, they cannot quantify the dose–response relationship between levels of alcohol consumption and mortality [\[51\]](#page-10-7). Several limitations specific to the genetic underpinnings of Mendelian randomization analyses do not allow them to be fully equiparated to randomized trials [\(#page-10-7)[–53\]](#page-10-8). Some assumptions of the MR analyses have been challenged when analogies for achieving causal inferences have been made between the effect of the genetic variant in a MR study and the intention-to-treat effect in a randomized controlled trial (RCT). There are four weaknesses in such an analogy, as reported elsewhere in further detail [\[53\]](#page-10-8). First, the compared groups with different genetic variants in MR may not be balanced, as they are in large RCTs, because of linkage disequilibrium, population stratification, or other reasons. Second, the genetic variant is not always causal, but it might only be a misclassified version of an assigned treatment strategy and the important assumption of a strong homogeneity effect within each group required for the use of instrumental variables is usually not met in MR studies because it would be biologically implausible. Third, the definition of treatment "adherence" (that permits one to differentiate between intention-totreat and per-protocol analyses) is unclear in MR and cannot be properly defined because the treatment strategies are not explicitly described. Fourth, and very importantly, "time zero" of follow-up (i.e., the inception instant in a trial) is usually not well defined in a MR analyses. In a R## Communities:

### Alcohol Consumption and Its Associations with Sleep Disturbance, Fear Avoidance, Financial Level, and Mental Health
### Summary
This report examines the relationships between alcohol consumption and various factors, including sleep disturbance, fear avoidance, financial level, and mental health. The analysis reveals potential associations, correlations, and influences between alcohol consumption and these factors, shedding light on the complex interplay between alcohol use and other aspects of an individual's life.
### Key Findings
Alcohol consumption may be associated with sleep disturbances: The text suggests that alcohol consumption may be associated with various sleep disturbances, including insomnia, obstructive sleep apnea, circadian abnormalities, short sleep duration, and poor sleep quality. Alcohol consumption, particularly binge drinking, has been linked to adverse health effects and sleep problems.
Alcohol consumption may affect fear avoidance beliefs: The text indicates that alcohol consumption may affect fear avoidance beliefs, potentially contributing to increased fear avoidance. This may be due to impaired judgment or increased risk-taking associated with alcohol use.
Alcohol consumption may be associated with financial level: The text suggests that there may be an association between financial level and alcohol consumption, as financial constraints can affect the ability to afford alcohol. However, the relationship is not explicitly stated, and it is possible that financial level could influence alcohol consumption.
Alcohol consumption may be associated with increased anxiety: The text indicates that anxiety is often associated with increased alcohol consumption. This may be due to alcohol's sedative effects, which can temporarily reduce anxiety, leading to increased consumption. However, long-term alcohol use can exacerbate anxiety symptoms.
Alcohol consumption may be associated with depression: The text suggests that alcohol consumption may be associated with depression. This may be due to alcohol's effects on the brain, which can lead to mood changes and depressive symptoms. Long-term alcohol use can also contribute to depression.

### Obesity and Body Mass Index (BMI) Community
### Summary
This report focuses on the community of obesity and Body Mass Index (BMI), two interconnected entities that play significant roles in human health. The community is characterized by the relationships between obesity and BMI, including causation, association, correlation, and measurement. The entities are also associated with various health conditions, such as chronic back pain, cancer, and kidney disease, as well as factors like genetics, sedentary behavior, and socioeconomic deprivation.
### Key Findings
Obesity is a condition characterized by excess body fat, measured by a BMI of 30 or higher.: Obesity is a health condition that is defined by an excess amount of body fat. This excess body fat is measured using the Body Mass Index (BMI), which is calculated by dividing an individual's weight in kilograms by the square of their height in meters.
BMI is a measure of body fat based on height and weight.: BMI is a measure used to determine an individual's body fat based on their height and weight. It is calculated by dividing an individual's weight in kilograms by the square of their height in meters.
Obesity is associated with increased BMI.: A higher BMI is indicative of a higher amount of body fat, and individuals with obesity have a BMI of 30 or higher.
BMI is causally associated with obesity.: A high BMI is a cause of obesity, as it indicates an excess amount of body fat.
BMI is correlated with obesity.: A higher BMI is associated with a greater likelihood of being obese.
BMI is used to determine obesity.: BMI is a measure used to identify individuals with obesity, as a BMI of 30 or higher indicates obesity.
BMI is a measure of obesity.: BMI is a measure used to quantify the amount of body fat in an individual, and a high BMI is indicative of obesity.
BMI is a measure of body weight.: BMI is a measure used to determine an individual's body weight, and a high BMI is indicative of excess body weight.
BMI is a measure of body fat.: BMI is a measure used to determine the amount of body fat in an individual, and a high BMI is indicative of excess body fat.
BMI is a measure of obesity risk.: A higher BMI is associated with an increased risk of obesity, as it indicates a higher amount of body fat.

### Depression and its Associated Health Outcomes
### Summary
This report examines the community of depression, its subtypes, and its associations with various health outcomes, including arthritis, asthma, hypertension, heart disease, chronic physical conditions, osteoporosis, headache, COPD, and other comorbidities. The community also includes entities such as job strain, unemployment, widowhood, environmental risk factors, and psychotropic medications. The report provides insights into the causal relationships, risk factors, and bidirectional relationships between depression and these health outcomes.
### Key Findings
Depression is associated with an increased risk of developing arthritis: The text suggests that there is a strong association between depression and arthritis. Depression has been associated with an increased risk of developing arthritis, as well as an increased risk for arthritis in general. This association is supported by type II evidence.
Depression is associated with an increased risk of developing asthma: Depression has been associated with an increased risk of developing asthma. This association is supported by type II evidence.
Depression is associated with an increased risk of developing hypertension: Depression has been associated with an increased risk of developing hypertension. This association is supported by type II evidence.
Depression is associated with an increased risk of developing heart disease: Depression has been associated with an increased risk of developing heart disease. This association is supported by type II evidence.
Depression is associated with an increased risk of developing chronic physical conditions: The text suggests that depression is associated with an increased risk for chronic physical conditions. The study found that depression was associated with an increased risk of chronic physical conditions.
Depression is associated with an increased risk of developing osteoporosis: Depression has been associated with an increased risk of developing osteoporosis. This association is supported by type II evidence.
Depression is associated with an increased risk of headache: Depression is associated with an increased risk of headache. Depression was identified as a predisposing contributor for the risk of headache, and depression is a significant contributor to headache.
Depression is associated with an increased risk of COPD: Depression has been associated with an increased risk of developing COPD. Depression has been associated with an increased risk of COPD, and depression and COPD often occur together, with depression exacerbating the symptoms of COPD.
Depression is associated with unemployment: Unemployment has been identified as a risk factor for depression. The text suggests that individuals with depression may have problems with access to primary care, which can increase the risk of chronic physical conditions, and unemployment has been associated with an increased risk of depression.
Depression is associated with widowhood: Widowhood is significantly associated with depression. Widowhood is a known risk factor for depression, and widowhood is a risk factor for developing depression.

### Community of Adults and Their Mental Health
### Summary
This report focuses on the community of adults, aged 18 years or older, and their mental health. The community is composed of various racial and ethnic subgroups, including Asian, White, Multiracial, Hispanic, and Black or African American. The report examines the prevalence of mental health issues, substance use disorders, and mental health treatment among these subgroups. It also compares the mental health status of young adults, aged between 18 and 35, to the overall adult population.
### Key Findings
Prevalence of Mental Health Issues: The report indicates that a significant number of adults suffer from mental health issues, including any mental illness (AMI) and serious mental illness (SMI). The prevalence of these issues varies among racial and ethnic subgroups, with Multiracial individuals having the highest percentage of AMI and SMI.
Substance Use Disorders: The report also discusses the prevalence of substance use disorders among adults. The most commonly abused substances include marijuana, cocaine, heroin, methamphetamine, prescription psychotherapeutic drugs, and hallucinogens. The prevalence of substance use disorders also varies among racial and ethnic subgroups.
Mental Health Treatment: The report shows that a significant number of adults receive mental health treatment, including prescription medication and substance use treatment. The availability and accessibility of mental health treatment vary among racial and ethnic subgroups.
Comparison of Young Adults and Adults: The report compares the mental health status of young adults to the overall adult population. Young adults are found to have a higher prevalence of mental health issues and substance use disorders compared to the overall adult population.
Racial and Ethnic Differences: The report compares the mental health status of various racial and ethnic subgroups. Some differences are found in the prevalence of mental health issues, substance use disorders, and mental health treatment among these subgroups.

### Research Community on Comorbidity Burden and Healthcare Costs in Obesity
### Summary

In [56]:
print(report)

# Report:
## Chunks:

 al.,](#page-7-3) [2012\)](#page-7-3), and *moderate drinkers* (34.8%; defined as *current drinkers* who that have less than or equal to 210 g of ethanol per week). #### Genetic Instruments There are two genetic variants commonly used in MR studies of alcohol use: the alcohol dehydrogenase 1B gene (*ADH1B* rs1229984) and the aldehyde dehydrogenase 2 gene (*ALDH2* rs671), both of which encode enzymes involved in the metabolic pathway for ethanol and can change the metabolic balance of acetaldehyde in human body ([Peng and Yin, 2009\)](#page-7-5). In the human body, ethanol is first converted to acetaldehyde by alcohol dehydrogenase (ADH) and then to acetate by aldehyde dehydrogenase (ALDH). The enzyme activity of ADH and ALDH are largely determined by the number of effect alleles (i.e., A-allele) in both *ADH1B* rs1229984 and *ALDH2* rs671. In East Asian populations, *ALDH2* rs671 alleles exist with three genotypes, GG (# of A allele = 0), AG (# of A allele = 1), and AA (# of A allele = 2), where the presence of A allele can significantly decrease the detoxification of acetaldehyde generated during alcohol metabolism in humans as noted above ([Peng and Yin, 2009](#page-7-5); [Edenberg and McClintick, 2018\)](#page-6-10). From **[Table 1](#page-2-0)**, 35.5% of respondents in our sample are A-allele carriers (i.e., genotypes of AA and AG). Specifically, the percentages of genotype AA and AG are 4.5 and 31.0%, respectively. In European populations, *ADH1B* rs1229984 has been used as the principal genetic instrument in MR studies of alcohol use ([Holmes et al., 2014](#page-6-7)). But because the proportion of A-allele carriers is very low (around 3% in Europeans), these MR studies require much larger sample sizes.(#page-3-0) In comparison, a majority of participants are A-allele carriers of the *ADH1B* rs1229984 in our sample (AA: 42.4% and AG: 44.8%). # Measures of Depression The 10-item Center for Epidemiologic Studies Depression Scale (CESD-10) was used as a reliable and valid survey instrument to screen for symptoms of depression [\(Radloff, 1977;](#page-7-6) [Boey,](#page-6-11) [1999\)]
>de<br>for<br>l ef<br>fec<br>No<br>evi<br>ts<br>ar<br>nce<br>ca<br>usa | | 34 | Rit<br>chi<br>l.<br>t a<br>e e<br>(<br>4)<br>201 | Alc<br>oh<br>ol | Ind<br>ivid<br>ual<br>lev<br>el | Alc<br>oh<br>ol<br>in<br>da<br>use<br>gra<br>m<br>per<br>y<br>(se<br>lf-r<br>rt)<br>epo | itiv<br>e f<br>tio<br>nin<br>(<br>in-<br>Co<br>gn<br>unc<br>g<br>per<br>son<br>12)<br>Mo<br>Ho<br>Tes<br>t N<br>ray<br>use<br>o. | – | cle<br>evi<br>de<br>for<br>l ef<br>fec<br>No<br>ts<br>ar<br>nce<br>ca<br>usa<br>of<br>alc<br>oh<br>ol o<br>nit<br>ive<br>fun<br>ctio<br>nin<br>n c<br>og<br>g,<br>her<br>int<br>ctio<br>Ho<br>, t<br>we<br>ver<br>e w<br>as<br>an<br>era<br>n<br>h t<br>hat<br>ind<br>ivid<br>ual<br>ith<br>hig<br>her<br>suc<br>s w<br>eti<br>bili<br>lco<br>ho<br>l<br>ty<br>to<br>gen<br>c a<br>pro<br>ces<br>s a<br>sho<br>d r<br>ela<br>tive<br>im<br>s in<br>ent<br>we<br>pro<br>vem<br>nit<br>ive<br>ab<br>ility<br>wit<br>h m<br>cog<br>ore<br>tio<br>wh<br>tho<br>wit
·667% | 0·253% | 25·7 | 11·1% | 0·119% | | | (0·619 to 3·79) | (0·233 to 1·43) | (–0·161 to 0·738) | (17·3 to 36·8) | (7·45 to 15·9) | (–3·42 to 3·33) | | Mexico | | | | | | | | 15–39 years | 6570 | 25·2% | –2·75% | 15000 | 59·7% | –4·61% | | 40–64 years | (3930 to 8740) | (15·1 to 33·5) | (–10·3 to 4·67) | (12 200 to 16100) | (48·4 to 64·1) | (–10·3 to 1·09) | | | 1180 | 6·50% | –0·343% | 7170 | 43·7% | –5·88% | | ≥65 years | (659 to 1850) | (3·64 to 10·3) | (–3·94 to 2·67) | (6040 to 8670) | (36·8 to 52·8) | (–11·7 to –0·361) | | | 69·8 | 1·26% | 0·498% | 868 | 18·3% | –0·0786% | | | (25·6 to 150) | (0·463 to 2·71) | (–0·245 to 1·23) | (630 to 1170) | (13·3 to 24·7) | (–4·86 to 4·23) | | Nicaragua | | | | | | | | 15–39 years | 254 | 18·0% | –1·28% | 781 | 55·3% | –1·14% | | | (133 to 365) | (9·44 to 25·9) | (–8·09 to 4·69) | (593 to 854) | (42·0 to 60·5) | (–7·11 to 4·62) | | 40–64 years | 36·0 | 4·79% | 0·851% | 253 | 38·4% | –1·55% | | | (18·1 to 62·8) | (2·41 to 8·36) | (–1·69 to 2·94) | (204 to 323) | (30·9 to 48·9) | (–8·40 to 4·42) | | ≥65 years | 1·55 | 0·729% | 0·420% | 23·6 | 13·6% | 1
 a slight but noticeable association with pain reduction and mitigation of physical dysfunction [\(#page-9-5)]. Terefore, researchers are increasingly recognizing the intricate comorbidities and interactions between pain and mental disorders, where the two diseases often coexist and promote each other, and may be partially mediated by shared neural mechanisms [(#page-9-6)]. Addressing both the physical and psychological aspects of pain is crucial for managing this condition efectively and improving patients' quality of life. It has been reported [\(#page-9-7)] that there is a strong correlation between the prevalence of depression and the severity of pain in patients with lower back pain. Patients with severe pain experience higher levels of mental distress than those with mild or moderate pain. Moreover, observational studies [[9,](#page-9-8) [10\]](#page-9-9) have also found that the use of opioids is highly comorbid with depression, anxiety, and stress related disorders. Tese fndings underscore the importance of psychological interventions as an integral component of pain management, which can improve patients' mental health, help alleviate pain, and reduce reliance on opioids, and may be a potential alternative to medication analgesia in some cases [(#page-9-10)]. Despite previous research on the relationship between pain and psychological problems, the fndings have been inconclusive, and our understanding of this complex interaction remains limited. A recent MR study [(#page-9-11)] has identifed depression as a risk factor for pain localized in specifc regions, including the head, neck/shoulder, back, and abdomen/stomach. However, whether there are causal associations between other mental disorders and pain remain uncertain, which may pose challenges for further clinical application of psychological intervention. Addressing this gap in research through rigorous and systematic investigation of the complexities of the relationship between pain and mental health is necessary to develop efective and targeted psychological interventions that can beneft patients in need. Mendelian randomization (MR) involves the use of single nucleotide polymorphism (SNP) as instrumental variables to estimate the causal efect of exposure factors on outcomes [\(#page-9-12)]. Tis method is advantageous because genetic variants are randomly allocated during meiosis, minimizing confounding, measurement error, and reverse causation that can afict conventional multivariable regression approaches [[14\]](#page-9-13). Moreover, the genetic variations used in MR analyses are unrelated to confounding variables in the exposure-outcome relation, reducing the risk of bias, and enhancing the validity of causal inference [\(#page-9-14)]. Given the critical public health implications of assessing the bidirectional relationship between pain and mental disorders, obtaining robust causal inferences about these associations is critical for developing efective prevention and treatment strategies. Te primary aim of the study is to update and expand upon previous research
\]](#page-10-2). However, these cohorts included highly selected middle-to-high class subjects, highly educated subjects, or only health professionals. They also reported J-shaped associations for all-cause mortality. These effects might be dependent on the distribution of causes of death in the selected samples and on the distribution of levels of alcohol consumption in cohort participants, with few of them drinking high amounts or indulging in binge drinking [\[11\]](#page-9-0). This fact may compromise the strength of their potential causal inferences and generalizability [\(#page-10-3)[–46\]](#page-10-4). In addition, studies using genetic instrumental variables or Mendelian randomization (MR) analyses have challenged that moderate alcohol consumption may reduce CVD or total mortality and support complete abstention as the healthiest option [\[47–](#page-10-5)[50\]](#page-10-6). These analyses avoid the problems of self-selection for the drinking pattern, thus reducing confounding. They also provide a proxy of lifetime consumption and eliminate reverse causation. There are also limitations in MR analyses because, while MR analyses may contribute to identifying causal pathways, they cannot quantify the dose–response relationship between levels of alcohol consumption and mortality [\[51\]](#page-10-7). Several limitations specific to the genetic underpinnings of Mendelian randomization analyses do not allow them to be fully equiparated to randomized trials [\(#page-10-7)[–53\]](#page-10-8). Some assumptions of the MR analyses have been challenged when analogies for achieving causal inferences have been made between the effect of the genetic variant in a MR study and the intention-to-treat effect in a randomized controlled trial (RCT). There are four weaknesses in such an analogy, as reported elsewhere in further detail [\[53\]](#page-10-8). First, the compared groups with different genetic variants in MR may not be balanced, as they are in large RCTs, because of linkage disequilibrium, population stratification, or other reasons. Second, the genetic variant is not always causal, but it might only be a misclassified version of an assigned treatment strategy and the important assumption of a strong homogeneity effect within each group required for the use of instrumental variables is usually not met in MR studies because it would be biologically implausible. Third, the definition of treatment "adherence" (that permits one to differentiate between intention-totreat and per-protocol analyses) is unclear in MR and cannot be properly defined because the treatment strategies are not explicitly described. Fourth, and very importantly, "time zero" of follow-up (i.e., the inception instant in a trial) is usually not well defined in a MR analyses. In a R## Communities:

### Alcohol Consumption and Its Associations with Sleep Disturbance, Fear Avoidance, Financial Level, and Mental Health
### Summary
This report examines the relationships between alcohol consumption and various factors, including sleep disturbance, fear avoidance, financial level, and mental health. The analysis reveals potential associations, correlations, and influences between alcohol consumption and these factors, shedding light on the complex interplay between alcohol use and other aspects of an individual's life.
### Key Findings
Alcohol consumption may be associated with sleep disturbances: The text suggests that alcohol consumption may be associated with various sleep disturbances, including insomnia, obstructive sleep apnea, circadian abnormalities, short sleep duration, and poor sleep quality. Alcohol consumption, particularly binge drinking, has been linked to adverse health effects and sleep problems.
Alcohol consumption may affect fear avoidance beliefs: The text indicates that alcohol consumption may affect fear avoidance beliefs, potentially contributing to increased fear avoidance. This may be due to impaired judgment or increased risk-taking associated with alcohol use.
Alcohol consumption may be associated with financial level: The text suggests that there may be an association between financial level and alcohol consumption, as financial constraints can affect the ability to afford alcohol. However, the relationship is not explicitly stated, and it is possible that financial level could influence alcohol consumption.
Alcohol consumption may be associated with increased anxiety: The text indicates that anxiety is often associated with increased alcohol consumption. This may be due to alcohol's sedative effects, which can temporarily reduce anxiety, leading to increased consumption. However, long-term alcohol use can exacerbate anxiety symptoms.
Alcohol consumption may be associated with depression: The text suggests that alcohol consumption may be associated with depression. This may be due to alcohol's effects on the brain, which can lead to mood changes and depressive symptoms. Long-term alcohol use can also contribute to depression.

### Obesity and Body Mass Index (BMI) Community
### Summary
This report focuses on the community of obesity and Body Mass Index (BMI), two interconnected entities that play significant roles in human health. The community is characterized by the relationships between obesity and BMI, including causation, association, correlation, and measurement. The entities are also associated with various health conditions, such as chronic back pain, cancer, and kidney disease, as well as factors like genetics, sedentary behavior, and socioeconomic deprivation.
### Key Findings
Obesity is a condition characterized by excess body fat, measured by a BMI of 30 or higher.: Obesity is a health condition that is defined by an excess amount of body fat. This excess body fat is measured using the Body Mass Index (BMI), which is calculated by dividing an individual's weight in kilograms by the square of their height in meters.
BMI is a measure of body fat based on height and weight.: BMI is a measure used to determine an individual's body fat based on their height and weight. It is calculated by dividing an individual's weight in kilograms by the square of their height in meters.
Obesity is associated with increased BMI.: A higher BMI is indicative of a higher amount of body fat, and individuals with obesity have a BMI of 30 or higher.
BMI is causally associated with obesity.: A high BMI is a cause of obesity, as it indicates an excess amount of body fat.
BMI is correlated with obesity.: A higher BMI is associated with a greater likelihood of being obese.
BMI is used to determine obesity.: BMI is a measure used to identify individuals with obesity, as a BMI of 30 or higher indicates obesity.
BMI is a measure of obesity.: BMI is a measure used to quantify the amount of body fat in an individual, and a high BMI is indicative of obesity.
BMI is a measure of body weight.: BMI is a measure used to determine an individual's body weight, and a high BMI is indicative of excess body weight.
BMI is a measure of body fat.: BMI is a measure used to determine the amount of body fat in an individual, and a high BMI is indicative of excess body fat.
BMI is a measure of obesity risk.: A higher BMI is associated with an increased risk of obesity, as it indicates a higher amount of body fat.

### Depression and its Associated Health Outcomes
### Summary
This report examines the community of depression, its subtypes, and its associations with various health outcomes, including arthritis, asthma, hypertension, heart disease, chronic physical conditions, osteoporosis, headache, COPD, and other comorbidities. The community also includes entities such as job strain, unemployment, widowhood, environmental risk factors, and psychotropic medications. The report provides insights into the causal relationships, risk factors, and bidirectional relationships between depression and these health outcomes.
### Key Findings
Depression is associated with an increased risk of developing arthritis: The text suggests that there is a strong association between depression and arthritis. Depression has been associated with an increased risk of developing arthritis, as well as an increased risk for arthritis in general. This association is supported by type II evidence.
Depression is associated with an increased risk of developing asthma: Depression has been associated with an increased risk of developing asthma. This association is supported by type II evidence.
Depression is associated with an increased risk of developing hypertension: Depression has been associated with an increased risk of developing hypertension. This association is supported by type II evidence.
Depression is associated with an increased risk of developing heart disease: Depression has been associated with an increased risk of developing heart disease. This association is supported by type II evidence.
Depression is associated with an increased risk of developing chronic physical conditions: The text suggests that depression is associated with an increased risk for chronic physical conditions. The study found that depression was associated with an increased risk of chronic physical conditions.
Depression is associated with an increased risk of developing osteoporosis: Depression has been associated with an increased risk of developing osteoporosis. This association is supported by type II evidence.
Depression is associated with an increased risk of headache: Depression is associated with an increased risk of headache. Depression was identified as a predisposing contributor for the risk of headache, and depression is a significant contributor to headache.
Depression is associated with an increased risk of COPD: Depression has been associated with an increased risk of developing COPD. Depression has been associated with an increased risk of COPD, and depression and COPD often occur together, with depression exacerbating the symptoms of COPD.
Depression is associated with unemployment: Unemployment has been identified as a risk factor for depression. The text suggests that individuals with depression may have problems with access to primary care, which can increase the risk of chronic physical conditions, and unemployment has been associated with an increased risk of depression.
Depression is associated with widowhood: Widowhood is significantly associated with depression. Widowhood is a known risk factor for depression, and widowhood is a risk factor for developing depression.

### Community of Adults and Their Mental Health
### Summary
This report focuses on the community of adults, aged 18 years or older, and their mental health. The community is composed of various racial and ethnic subgroups, including Asian, White, Multiracial, Hispanic, and Black or African American. The report examines the prevalence of mental health issues, substance use disorders, and mental health treatment among these subgroups. It also compares the mental health status of young adults, aged between 18 and 35, to the overall adult population.
### Key Findings
Prevalence of Mental Health Issues: The report indicates that a significant number of adults suffer from mental health issues, including any mental illness (AMI) and serious mental illness (SMI). The prevalence of these issues varies among racial and ethnic subgroups, with Multiracial individuals having the highest percentage of AMI and SMI.
Substance Use Disorders: The report also discusses the prevalence of substance use disorders among adults. The most commonly abused substances include marijuana, cocaine, heroin, methamphetamine, prescription psychotherapeutic drugs, and hallucinogens. The prevalence of substance use disorders also varies among racial and ethnic subgroups.
Mental Health Treatment: The report shows that a significant number of adults receive mental health treatment, including prescription medication and substance use treatment. The availability and accessibility of mental health treatment vary among racial and ethnic subgroups.
Comparison of Young Adults and Adults: The report compares the mental health status of young adults to the overall adult population. Young adults are found to have a higher prevalence of mental health issues and substance use disorders compared to the overall adult population.
Racial and Ethnic Differences: The report compares the mental health status of various racial and ethnic subgroups. Some differences are found in the prevalence of mental health issues, substance use disorders, and mental health treatment among these subgroups.

### Research Community on Comorbidity Burden and Healthcare Costs in Obesity
### Summary

# Saving the Prompts

In [ ]:
import json

# variables of interest
with open("variable_definitions/default_definitions.json", "r") as file:
    def_map = json.load(file)

In [ ]:
from promptsd.query_prompts import plausibility_prompt, temporality_prompt, causal_lit_prompt, association_prompt

var1 = "Sex"
var2 = "Anxiety"

with open("raw_prompts/plausibility_prompt.txt", "w") as f:
    print(plausibility_prompt(var1, var2), file=f)

with open("raw_prompts/temporality_prompt.txt", "w") as f:
    print(temporality_prompt(var1, var2), file=f)

with open("raw_prompts/causal_lit_prompt.txt", "w") as f:
    print(causal_lit_prompt(var1, var2), file=f)

with open("raw_prompts/association_prompt.txt", "w") as f:
    print(association_prompt(var1, var2), file=f)

In [ ]:
pquery = plausibility_prompt(var1, var2)
aquery = association_prompt(var1, var2)
tquery = temporality_prompt(var1, var2)

In [ ]:
from prompts import *
with open("raw_prompts/kg+llm_prompt_plausibility.txt", "w") as f:
    print(reduce(pquery, var1, var2, "", def_map), file=f)

with open("raw_prompts/kg+llm_prompt_association.txt", "w") as f:
    print(reduce(aquery, var1, var2, "", def_map), file=f)

with open("raw_prompts/kg+llm_prompt_temporality.txt", "w") as f:
    print(reduce(tquery, var1, var2, "", def_map), file=f)

In [ ]:
with open("raw_prompts/llm+rag_prompt_plausibility.txt", "w") as f:
    print(reduce_rag(pquery, var1, var2, "", def_map), file=f)

with open("raw_prompts/llm+rag_prompt_association.txt", "w") as f:
    print(reduce_rag(aquery, var1, var2, "", def_map), file=f)

with open("raw_prompts/llm+rag_prompt_temporality.txt", "w") as f:
    print(reduce_rag(tquery, var1, var2, "", def_map), file=f)

In [ ]:
with open("raw_prompts/llm_prompt_plausibility.txt", "w") as f:
    print(predict(pquery, var1, var2,  def_map), file=f)

with open("raw_prompts/llm_prompt_association.txt", "w") as f:
    print(predict(aquery, var1, var2,  def_map), file=f)

with open("raw_prompts/llm_prompt_temporality.txt", "w") as f:
    print(predict(tquery, var1, var2,  def_map), file=f)